// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgBdoW84D5XZsywUMQOiruuc9nM6YSvnQ',
    appId: '1:723809517894:web:f1f54eee548c3ad7ec6547',
    messagingSenderId: '723809517894',
    projectId: 'kawaiibeats-9eedb',
    authDomain: 'kawaiibeats-9eedb.firebaseapp.com',
    storageBucket: 'kawaiibeats-9eedb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx8omDGNbIA2AIIn-28AMBd_LJS_71nl0',
    appId: '1:723809517894:android:c87cac393ccb224cec6547',
    messagingSenderId: '723809517894',
    projectId: 'kawaiibeats-9eedb',
    storageBucket: 'kawaiibeats-9eedb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYyv9qlSxsH_TxCmIp1Wdou0UnPDL6LCg',
    appId: '1:723809517894:ios:d6b5ba855c102e02ec6547',
    messagingSenderId: '723809517894',
    projectId: 'kawaiibeats-9eedb',
    storageBucket: 'kawaiibeats-9eedb.firebasestorage.app',
    iosBundleId: 'com.example.kawaiibeats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYyv9qlSxsH_TxCmIp1Wdou0UnPDL6LCg',
    appId: '1:723809517894:ios:d6b5ba855c102e02ec6547',
    messagingSenderId: '723809517894',
    projectId: 'kawaiibeats-9eedb',
    storageBucket: 'kawaiibeats-9eedb.firebasestorage.app',
    iosBundleId: 'com.example.kawaiibeats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgBdoW84D5XZsywUMQOiruuc9nM6YSvnQ',
    appId: '1:723809517894:web:f982d7277d86bbc4ec6547',
    messagingSenderId: '723809517894',
    projectId: 'kawaiibeats-9eedb',
    authDomain: 'kawaiibeats-9eedb.firebaseapp.com',
    storageBucket: 'kawaiibeats-9eedb.firebasestorage.app',
  );

}